object Versions {
    const val kotlin = "1.5.31"
    const val gradle = "7.0.3"
    const val coroutines = "1.5.2"
    const val ktx = "1.6.0"
    const val ktxFragment = "1.3.6"
    const val ktxViewModel = "2.3.1"
    const val ktxLifecycleRuntime = "2.4.0-alpha03"
    const val androidXJunit = "1.1.2"
    const val espresso = "3.3.0"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val ktlint = "10.0.0"
    const val dagger = "2.40.1"
    const val compose = "1.0.1"
    const val nav = "2.3.5"
    const val composeConstraint = "1.0.0-beta02"
    const val composeActivity = "1.3.1"
    const val composeViewModel = "1.0.0-alpha07"
    const val mmkv = "1.2.7"
    const val lottieVersion = "4.1.0"
    const val mavericksVersion = "2.4.0"
    const val detektVersion = "1.16.0"
}